openapi: 3.0.0

info:
  version: 1.0.0
  title: CMC-Hackathon-Team1-API
  description: '해커톤 TEAM1 API 명세서'

tags:
  - name: User
    description: 유저 도메인 관련 API들
  - name: Feed
    description: 피드 도메인 관련 API들
  - name: Notice
    descripion: 공지 도메인 관련 API들
  - name: Test
    description: 테스트 API

paths:
  /api/test:
    get:
      tags:
        - Test
      summary: 커넥션 테스트 API
      responses:
        '100':
          description: 테스트
          content: 
            application/json:
              schema:
                type: pong
                properties:
                  content: 
                    example:
    
  /api/feeds/feedList?profileId={profileId}&page={page}&pageSize={pageSize}:
    get:
      tags:
        - Feed
      summary: (마이페이지) 게시글 리스트 조회
      parameters:
        - in : query
          name: profileId
          securityschema:
            type: integer
                default: 1
                required: true
                description: 프로필 인덱스
        - in: query
          name: page
          securitySchemes:
            type: integer
                default: 11
                required: true
                description: 조회할 페이지 쪽 수
        - in: query
          name: pageSize
          securitySchemes:
            type: integer
                default: 11
                required: true
                description: 한 페이지에 조회할 데이터 수
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

  /api/feeds/feed?profileId={profileId}&feedId={feedId}:
    get:
      tags:
        - Feed
      summary: (마이페이지) 게시글 내용 조회
      parameters:
        - in : query
          name: profileId
          securityschema:
            type: integer
                default: 1
                required: true
                description: 프로필 인덱스
        - in: query
          name: feedId
          securitySchemes:
            type: integer
                default: 11
                required: true
                description: 피드 인덱스
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

# 프로필 생성
  /api/users/create:
    post:
      tags:
        - User
      summary: 프로필 생성(페르소나)
      parameters:
        - in: body
          name: CreateProfileParams
          description: 프로필 생성 파라미터
          schema:
              type: object
              required:
                - userId
                - personaId
                - nickname
                - introduction
                - profileImgUrl
              properties:
                    userId:
                        description: 유저 인덱스
                        type: int
                        default: 1
                    personaId:
                        description: 페르소나 인덱스
                        type: int
                        default: 2
                    nickname:
                        description: 유저 닉네임
                        type: String
                        default: "BLUE"
                    introduction:
                        description: 유저 소개글
                        type: String
                        default: "유저 소개글을 작성해주세요!"
                    profileImgUrl:
                        description: 유저 이미지
                        type: String
                        default: "ProfileImgUrl"
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

# 프로필 변경 (다른 페르소나 정보 가져오기)
  /api/users/persona?profileId={profileId}:
    get:
      tags:
        - User
      summary: 프로필 변경 (다른 페르소나 정보 가져오기)
      parameters:
        - in : query
          name: profileId
          securityschema:
              type: integer
          default: 1
          description: 프로필 인덱스
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.
          


# 유저 모든 페르소나 불러오기
  /api/users/{userId}/profile:
    get:
      tags:
        - User
      summary: 유저 모든 페르소나 불러오기
      parameters:
          - in: path
            name: userId
            default: 1
            schema :
                type: integer
            example: 1
            required: true
            description: 유저 인덱스
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.


# 한달간 공감, 글, 팔로우 횟수 count API
  /api/users/{userId}/profile/statistics:
    get:
      tags:
        - User
      summary: 한달간 공감, 글, 팔로우 횟수 count API
      parameters:
          - in: path
            name: userId
            default: 1
            schema :
                type: integer
            example: 1
            required: true
            description: 유저 인덱스
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

# 게시글 쓰기
  /api/feeds/feed:
    post:
      tags:
        - Feed
      summary: 게시글 쓰기
      parameters:
        - in: body
          name: CreateFeed
          description: 게시글 생성 파라미터
          schema:
              type: object
              required:
                - category
                - hashtag
                - content
                - status
                - imgUrl
              properties:
                    category:
                        description: 카테고리 명입니다. 정해진 카테고리 명만 입력하세요.
                        type: String
                        default: "문화 및 예술"
                    hashtag:
                        description: 하나의 String 안에 ‘, ‘를 기준으로 여러 해시태그를 넣어도 됩니다. (꼭 쉼표+빈칸 한칸 으로 구분해야함) 하나만 넣어도 됩니다. 근데 아직 해시태그 기능은 완벽하지 않습니다!
                        type: String
                        default: "#개발"
                    content:
                        description: 게시물 내용
                        type: String
                        default: "게시물 내용을 입력합니다~!"
                    status:
                        description: 비공개 설정 여부 입니다. ('private' or 'active')
                        type: String
                        default: "private"
                    imgUrl:
                        description: 게시글 이미지
                        type: String
                        default: "ProfileImgUrl"
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.



# 게시글 삭제
  /api/feeds/feed/{feedId}:
    delete:
      tags:
        - Feed
      summary: 게시글 삭제
      parameters:
          - in: path
            name: feedId
            default: 1
            schema :
                type: integer
            example: 1
            required: true
            description: 피드 인덱스
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

# (프로필 별)달력에서 게시글 존재 여부들 가져오기
  /api/calendars?year={year}&month={month}:
    get:
      tags:
        - Feed
      summary: (프로필 별)달력에서 게시글 존재 여부들 가져오기
      parameters:
          - in: path
            name: year
            default: 2022
            schema :
                type: integer
            example: 2022
            required: true
            description: 1900 ~ 2100까지의 숫자만 입력 가능
          - in: path
            name: month
            default: 09
            schema :
                type: integer
            example: 09
            required: true
            description: 1~12까지 가능, 일의 자리더라도 0을 붙여주셔야함!!
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.

# 공지사항
  /api/notice?page={page}:
    get:
      tags:
        - Notice
      summary: 공지사항
      parameters:
        - in : query
          name: page
          securityschema:
            type: integer
                example: 1
                required: true
                description: 페이징 용 변수, 안주셔도 되고, 넣어주시면, 10개씩 끊어서 나옵니다.
      responses:
        '100':
          description: 로그인 성공
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  isSuccess: 
                    example: true
                  code:
                    example: 100
                  message:
                    example: 성공
        '212':
          description: userId를 입력해주세요
        '227':
          description: userId는 최대 20자리를 입력해주세요
        '228':
          description: userId는 최대 3자리 이상 입력해주세요
        '221':
          description: 비밀번호를 입력 해주세요.
        '222':
          description: 비밀번호는 6~20자리를 입력해주세요
        '223':
          description: 비밀번호는 특수문자를 포함해야 합니다.